#!/usr/bin/env python

import sys

from rqt_robochoto.map_module import MineMapPlugin
from rqt_gui.main import Main

plugin = 'rqt_robochoto'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))