#!/usr/bin/env python

import sys

from rqt_monitor_robochoto.monitor_module import MonitorPlugin
from rqt_gui.main import Main

plugin = 'rqt_monitor_robochoto'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))